theme = "vim_dark_high_contrast"

[editor]
gutters = ['diff', 'diagnostics', 'line-numbers', 'spacer']
line-number = 'relative'
scrolloff = 5
auto-completion = true
auto-format = true
color-modes = true
popup-border = 'all'
bufferline = 'always'
middle-click-paste = true
idle-timeout = 100


[editor.cursor-shape]
insert = 'bar'
normal = 'block'
select = 'underline'

[editor.statusline]
left = ['mode', 'spinner']
center = ['file-name']
right = ['diagnostics', 'selections', 'position', 'file-encoding', 'file-line-ending', 'file-type']
separator = "|"
mode.normal = 'NORMAL'
mode.insert = 'INSERT'
mode.select = 'SELECT'

[editor.lsp]
enable = true
snippets = true
display-messages = true
auto-signature-help = false

[editor.smart-tab]
enable = true

[keys.insert]
'C-[' = 'normal_mode'

[editor.file-picker]
hidden = false

[keys.normal]
space.e = "signature_help"
"backspace" = ["collapse_selection", "keep_primary_selection"]
